### PR TITLE
Add testing

### PR DESCRIPTION
**Pull request by cmodijk**
**Changes**
* Drop support for PHP 5.6 and 7.0 #5
* Drop support for old symfony versions #6 
* Test support lowest posible version of a package
* Remove the PHPUnit 6.0 bridge
* Add composer and phpunit configuration
* Added travis ci #4

**DONE**
- [x] Replace `DefinitionDecorator` with `ChildDefinition` for symfony 4 
- [x] Fix all the symfony 4 support error's 
- [x] Add different versions of doctrine for testing
- [x] Check if we can implement idea's of [https://github.com/symfony/symfony-docs/pull/8701](https://github.com/Nyholm/symfony-docs/blob/8d33c153eb7528e2953eae6bac98ace23355fd5f/bundles/best_practices.rst#travis)

### CODE REVIEW

**Comment by cmodijk** [comment]
@ruudk We still need to fix a bunch of tests but it is a start

**Comment by caciobanu** [comment]
https://github.com/SimpleBus/SimpleBus/pull/20/files should fix some errors. If you need you can cherry pick this commit: https://github.com/caciobanu/SimpleBus/commit/00b1a74b892657c86bf7e5b2a79cf204eeeeb9cb

**Comment by caciobanu** [comment]
Failing **SimpleBus/RabbitMQBundleBridge** tests are related to https://github.com/php-amqplib/RabbitMqBundle/pull/509.

**Comment by cmodijk** [comment]
@caciobanu Thanks i merged your pull request and rebased mine to have these fixes

**Comment by cmodijk** [comment]
The `BernardBundleBridge` also has some know issues with it we consider dropping this bundle al together.

**Comment by caciobanu** [comment]
Issues with jms annotations should be fixed by using a PHPUnit boostrap file like https://github.com/SimpleBus/SimpleBus/blob/master/Bundle/JMSSerializerBundleBridge/tests/bootstrap.php

**Comment by cmodijk** [comment]
@caciobanu Thanks added the bootstrap file

**Comment by caciobanu** [comment]
For SimpleBus/RabbitMQBundleBridge we can make the service **old_sound_rabbit_mq.parts_holder** in the functional tests.

**Comment by caciobanu** [comment]
Here is a commit for fixing rabbitmq related tests: https://github.com/caciobanu/SimpleBus/commit/353453593e9ceaedfc80141ff316d77db95a4c89#diff-6957879f7f95fa4d1c3cd9df5d7e35f3

**Comment by cmodijk** [comment]
@caciobanu Thanks again! I changed this in the `config.yml`

**Comment by caciobanu** [comment]
I think that RabbitMQBundleBridge failures are related to https://github.com/SimpleBus/SimpleBus/blob/master/Bundle/RabbitMQBundleBridge/tests/bootstrap.php#L5. We should do a recursive find for an autoloader.

**Comment by cmodijk** [comment]
The tests seems to be "green" now but there are some problems that we need to solve. But i think we should merge this to get the first testing in and make new issues solving these issues;
- [ ] Fix tests and Symfony profiler intergration 
- [ ] Find a way to test the `prefer-lowest`
- [ ] Drop Support for Doctrine 2.2/2.3/2.4

**Comment by caciobanu** [comment]
+1 from me. I think it is a good plan.

**Comment by cmodijk** [comment]
Done, Merged and created issues for the open items

**Pull request merged**
