### PR TITLE
Remove deprecated `symfony/proxy-manager-bridge`

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ruudk** [comment]
I have no idea what the purpose was of this proxy detection. Since it's deprecated and I'm not `CollectsEventsFromEntities` I  think we should just get rid of it.

**Comment by cmodijk** [comment]
@ruudk With the `CollectsEventsFromEntities` it is possible to `record(` domain events inside a doctrine entity to be then shipped with SimpleBus events to a listener after the `flush` of doctrine happens. But what the purpose of the `symfony/proxy-manager-bridge` bridge was is something i can't remember at this time. I have to look into the original code and when this was added back in the day. Let me check this later this week and get back to you.

**Comment by cmodijk** [comment]
It was introduced here https://github.com/SimpleBus/symfony-bridge/commit/887c54c5030337b863a00c39bead8abd24dd7e54 in https://github.com/SimpleBus/symfony-bridge/pull/58

**Comment by cmodijk** [comment]
Seems like https://github.com/symfony/doctrine-bridge/blob/6.3/ManagerRegistry.php needed a proxy and the `symfony/proxy-manager-bridge` provided some stuff extra but is not needed anymore.

**Comment by ruudk** [comment]
Great! Thanks for checking.

I think this is still needed for 5.4.

Going to drop that release, oke?

**Comment by ruudk** [comment]
Do you know if the doctrine-bridge on 5.4 also needs it ?

**Review by cmodijk — APPROVED** [review]

**Comment by cmodijk** [comment]
It does not seem to me needed anymore

**Pull request merged**
