### PR TITLE
Remove data collector

### PR DESCRIPTION
**Pull request by ruudk**
It's looking for a BusRegistry that does not exist.

We never released a new version of the SymfonyBridge since we moved to the mono repo. 

Now that I tagged https://github.com/SimpleBus/SymfonyBridge/releases/tag/v5.1.3 I found out that it's broken and is looking for a `BusRegistry`.

Instead of fixing this my plan is to remove this completely as it's not working and I have no idea how it was intendend to work.

### CODE REVIEW

**Comment by cmodijk** [comment]
This was a pull request we merged before we moved to the mono repo and it was used for #30 and #21

**Comment by ruudk** [comment]
Do you know how to fix it because now we have a broken tagged release

**Comment by cmodijk** [comment]
Hmm my "rework" branch fixed some issues but i don't remember where I left back when i started #30. I did not create the original pull request and if you ask me we should merge this and close all the other issues. If someone want's to add a profiler they can start over. The symfony profiler has also changed a lot since then so i don't even think the old code still works.

**Comment by ruudk** [comment]
Agreed

**Pull request merged**
