### PR TITLE
WIP: feat: Add PHP 8 support

### PR DESCRIPTION
**Pull request by samijnih**
WIP

### CODE REVIEW

**Comment by cmodijk** [comment]
There are multiple `composer.json` files can you update all of them to allow PHP `8.0`?

Schermafbeelding 2020-12-08 om 20 37 04

**Comment by cmodijk** [comment]
@ruudk I was just checking the `master` branch but the latest `master` also failed?
*https://travis-ci.org/github/SimpleBus/SimpleBus/builds/668726196*

**Comment by samijnih** [comment]
> There are multiple `composer.json` files can you update all of them to allow PHP `8.0`? The project is sub split in different repositories that are available on packages.org.
> 
> Schermafbeelding 2020-12-08 om 20 37 04

Yes I've changed all travis and composer files. I just wanted to look if I could add support for each directory into separated commit and check for the CI to pass.

Actually master also fails yes.

I can push everything if you want :)

**Comment by cmodijk** [comment]
>Yes I've changed all travis and composer files. I just wanted to look if I could add support for each directory into separated commit and check for the CI to pass.

Aah oke, did not think of that. But i'm pretty sure you need the root `composer.json` to be updated the unit tests only run using the root `composer.json`. So yeah i would just push all and wait for travis to report back.

Thx in advance for taking the time!

**Comment by samijnih** [comment]
I think there could be conflicts with some dependencies. PHP 8 has just released few days ago and some Symfony packages are not supporting it yet... So wait and see :)

I've also added Symfony 5.1 and 5.2 versions to check interoperability

**Comment by cmodijk** [comment]
Oke, thanks for taking the time. I'm also looking into moving from travis to Github actions right know maybe we could faster feedback that way

**Comment by ruudk** [comment]
@cmodijk Maybe we can follow the approach I'm working on with LongRunning. That one uses GA together with Symplify Monorepo Builder to auto sync the root composer as well. Work in progress though...

**Comment by cmodijk** [comment]
@ruudk Yep, i'm copy pasting your work ;-)

*https://github.com/SimpleBus/SimpleBus/pull/88*

**Comment by cmodijk** [comment]
I'm closing this in favor of https://github.com/SimpleBus/SimpleBus/pull/88 I added PHP `8.0` support there @samijnih thx for your time

**Comment by samijnih** [comment]
> 
> 
> I'm closing this in favor of #88 I added PHP `8.0` support there @samijnih thx for your time

Np, thanks for taking the time to add that support 💯

**Pull request closed without merging**
