### PR TITLE
Remove the `CompilerPassUtil` and simply add the compiler passes with a priority

### PR DESCRIPTION
**Pull request by sroze**
The logic in the `CompilerPassUtil::prependBeforeOptimizationPass` method is actually wrong: it removes the priorities and prevent any accurate addition to the compiler passes after this has been done.

As the point of it was to be able to add a compiler pass at the very beginning of the chain, I suggest to simply use the priority 150, as Symfony's ones are 100 and bellow.

### CODE REVIEW

**Comment by xphere** [comment]
This behavior also breaks an otherwise simple flow: I can't  use `autoconfigure` to mark my services as `command_handlers` or `event_subscribers`, because when flattening the compiler passes Symfony's `ResolveInstanceofConditionalsPass` loses it's higher priority and will execute after SimpleBus' `AutoRegister`.

**Comment by cmodijk** [comment]
@sroze I updated your branch with our latest master branch but it seems that it is still needed for the 2.8 version of Symfony. Should we keep the class and only us it in the older Symfony versions?

**Comment by morticue** [comment]
@cmodijk Can this be merged? Since this lib already require atleast v3.3 of `symfony/dependency-injection`. So it does not need to be compatible with v2.8 any longer.

**Comment by morticue** [comment]
Perhaps I should mention @ruudk instead of the above question.

**Comment by ruudk** [comment]
Merged in https://github.com/SimpleBus/SimpleBus/pull/82

**Pull request closed without merging**
